import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import Typewriter from "typewriter-effect";

// components
import Layout from "@/components/layout";
import Heading from "@/components/heading";
import ResumeCard from "@/components/resumeCard";
import SkillComp from "@/components/skillComp";
import ProjectFrame from "@/components/projectFrame";
import ProjectCard from "@/components/projectCard";

// images
import kardinal from "../assets/projects/kardinal_project.png";
import afilename from "../assets/projects/afilename_project.png";
import appswaves from "../assets/projects/appswaves_project.png";
import fizz from "../assets/projects/fizz_project.png";
import car from "../assets/projects/car_flutter_app.png";

// icons
import LinkedInIcon from "@mui/icons-material/LinkedIn";
import ButtonComp from "@/components/buttonComp";
import GitHubIcon from "@mui/icons-material/GitHub";
import WhatsAppIcon from "@mui/icons-material/WhatsApp";
import MailIcon from "@mui/icons-material/Mail";
import FileDownloadIcon from "@mui/icons-material/FileDownload";
import CallIcon from "@mui/icons-material/Call";
import MenuIcon from "@mui/icons-material/Menu";
import ClearIcon from "@mui/icons-material/Clear";

export default function Home() {
  const [activeSection, setActiveSection] = useState();
  const navs = ["Home", "About Me", "Resume", "Portfolio", "Contact"];
  const phoneNumber = "03326556262";
  const email = "annasahmed1609@gmail.com";
  const linkedin = "annas-ahmed-3a2846207";
  const github = "AnnasAhmed1";
  const details = [
    { Name: "Annas Ahmed" },
    { Email: "annasahmed1609@gmail.com" },
    { Age: "21" },
    { From: "Karachi, Pakistan" },
  ];
  const education = [
    {
      year: "2021-2025",
      title: "BSCS",
      institue: "University Of Karachi",
      details: "Currently pursuing third year",
    },
  ];
  const experience = [
    {
      year: "August 2022 - Present",
      title: "FREELANCING",
      institue: "Different Freelance Platforms",
      details: "More than 1 year experience in Freelancing",
    },
  ];
  const skills = [
    { title: "React Js", percentage: 80 },
    { title: "Next Js", percentage: 70 },
    // { title: "Next Js", percentage: 70 },
    { title: "JavaScript", percentage: 80 },
    { title: "Python", percentage: 75 },
    { title: "MongoDB", percentage: 65 },
    { title: "Firebase", percentage: 65 },
    { title: "Node Js/Express Js", percentage: 50 },
    { title: "HTML/CSS", percentage: 95 },
  ];
  const socialLinks = [
    {
      icon: <WhatsAppIcon className="hover:text-green-600" fontSize="small" />,
      link: `https://api.whatsapp.com/send?phone=${phoneNumber}`,
    },
    {
      icon: <MailIcon className="hover:text-blue-700" fontSize="small" />,
      link: `mailto:${email}`,
      email: true,
    },
    {
      icon: <GitHubIcon className="hover:text-black" fontSize="small" />,
      link: `https://github.com/${github}`,
    },
    {
      icon: <LinkedInIcon className="hover:text-blue-800" fontSize="small" />,
      link: `https://www.linkedin.com/in/${linkedin}`,
    },
  ];
  const projects = [
    {
      image: fizz,
      liveLink: "https://fizzinnovations-portfolio.vercel.app/",
      githubLink: "Fizzinnovations_portfolio",
    },
    {
      image: appswaves,
      liveLink: "https://appswaves-3a882.web.app/",
      githubLink: "Appswaves_project",
    },
    {
      image: kardinal,
      liveLink: "https://kardinal-react-siraj.web.app/",
      githubLink: "Appswaves_project",
    },
    {
      image: afilename,
      liveLink: "https://afile-name-siraj.vercel.app/",
      githubLink: "AfileName-Siraj",
    },
  ];
  const [navOpen, setNavOpen] = useState(false);
  const handleSocialLinks = (link: string, email = false) => {
    !email ? window.open(link, "_blank") : (window.location.href = link);
  };
  const handleDownloadCV = () => {
    console.log("download");
    // Replace 'YourName_Resume.pdf' with the actual name of your CV file
    // const downloadLink = "/Annas_Ahmed_resume.pdf";
    // window.open(downloadLink, "_blank");
    // <a href="/Annas_Ahmed_resume.pdf" download="Annas_Ahmed_resume.pdf">
    //   Download CV
    // </a>;
    const downloadLink = "/Annas_Ahmed_resume.pdf";
    const a = document.createElement("a");
    a.href = downloadLink;
    a.download = "Annas_Ahmed_resume.pdf";
    a.click();
  };
  return (
    <>
      <Head>
        <title>Annas Ahmed</title>
        <meta name="description" content="Generated by Annas Ahmed" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
      </Head>
      <main className="flex">
        <section className="w-[250px] max-lg:hidden fixed flex flex-col h-screen overflow-hidden justify-between pt-10 pb-6 items-center px-4/ bg-[#111418]">
          <div className="flex justify-center items-center flex-col gap-4 ">
            <Image
              src={require("../assets/profile.png")}
              alt="Profile Picture"
              className="w-[180px] border-[8px] rounded-[50%] border-[#343a40]"
            />
            <h1 className="text-customLight text-2xl">Annas Ahmed</h1>
          </div>
          <nav className="my-10 ">
            <ul className="flex flex-col gap-4">
              {navs.map((nav: string, index: number) => {
                return (
                  <li
                    className="px-3 cursor-pointer text-customSemiLight text-lg text-center hover:text-customPrimary"
                    key={index}
                  >
                    {nav}
                  </li>
                );
              })}
            </ul>
          </nav>
          <div className="flex w-full justify-between items-center px-16 text-customSemiLight ">
            {socialLinks.map((social: any, index: number) => {
              return (
                <p
                  className="text-[8px] cursor-pointer"
                  key={index}
                  onClick={() => {
                    handleSocialLinks(social.link, social.email);
                  }}
                >
                  {social.icon}
                </p>
              );
            })}
          </div>
        </section>

        <div className="w-[calc(100%-250px)] max-lg:w-full ml-auto ">
          <nav className="hidden w-full z-[999]  max-lg:block bg-[#111418] py-4 px-[20px] fixed max-sm:px-[10px]">
            <div className="flex items-center">
              <h1 className="text-customLight font-[500] flex-1  text-2xl max-md:text-lg m-0">
                Annas Ahmed
              </h1>

              <div className="flex. w-full/ justify-between/ items-center/ px-16/ text-customSemiLight ">
                {socialLinks.map((social: any, index: number) => {
                  return (
                    <p
                      className="text-[8px]/ inline mr-4 max-sm:mr-2 cursor-pointer"
                      key={index}
                      onClick={() => {
                        handleSocialLinks(social.link, social.email);
                      }}
                    >
                      {social.icon}
                    </p>
                  );
                })}
              </div>
              <button
                onClick={() => {
                  setNavOpen(!navOpen);
                }}
                className="transition-all ease-linear duration-[0.5s]"
              >
                {!navOpen ? (
                  <MenuIcon className="text-white cursor-pointer transition-all ease-linear duration-[0.5s]" />
                ) : (
                  <ClearIcon className="text-white cursor-pointer transition-all ease-linear duration-[0.5s]" />
                )}
              </button>
            </div>
            <ul
              className={`${
                !navOpen ? "hidden" : "flex"
              } flex-col gap-1/ mt-10 mb-4 transition-all ease-linear duration-[0.5s] `}
            >
              {navs.map((nav: string, index: number) => {
                return (
                  <li
                    className={` cursor-pointer text-customSemiLight text-base py-3 ${
                      index !== navs.length - 1 || true
                        ? "border-b border-[#555555]"
                        : null
                    } text-center/ hover:text-customPrimary`}
                    key={index}
                  >
                    {nav}
                  </li>
                );
              })}
            </ul>
          </nav>
          <section
            id="welcomeSection"
            className={`flex-[8] /
            bg-[url(../assets/home_backgorund.jpeg)]
            bg-cover
            bg-no-repeat
            w-full
            h-screen
            `}
          >
            <div className="bg-[#252729] flex flex-col gap-8 max-md:gap-3 justify-center text-5xl max-md:text-4xl max-sm:text-3xl text-center font-bold tracking-wider items-center text-customLight bg-opacity-60 w-full h-screen">
              <h1 className="text-3xl max-md:text-xl max-sm:text-lg font-[500]">
                Welcome
              </h1>
              <Typewriter
                // component={[ <h1 className="text-5xl font-bold">I&apos;m Annas Ahmed.</h1>]}
                options={{
                  strings: ["I'm Annas Ahmed", "I'm a MERN Stack Developer"],
                  autoStart: true,
                  loop: true,
                }}
              />
              {/* <h1 className="">I&apos;m Annas Ahmed.</h1> */}
              <h1 className="text-2xl max-md:text-lg max-sm:text-base font-normal">
                from Karachi, Pakistan
              </h1>
              <ButtonComp text="Hire Me" transparent={true} />
            </div>
          </section>
          <Layout>
            <Heading text="Know Me More" subText="ABOUT ME" />
            <div className="flex max-md:flex-col max-md:gap-6 max-md:text-[14px] gap-12">
              <div>
                <h1 className="text-3xl max-sm:text-2xl font-[600]">
                  I&apos;m{" "}
                  <span className="text-customPrimary">Annas Ahmed,</span> a
                  MERN Stack Developer
                </h1>
                <p>
                  A passionate MERN stack developer with a year of freelancing
                  experience specializing in React.js and Next.js. I have a
                  profound love for crafting efficient, user-friendly, and
                  visually appealing web applications. With a solid foundation
                  in modern web development technologies, I&apos;m dedicated to
                  transforming ideas into functional, responsive, and engaging
                  digital experiences.
                </p>
                <p>
                  Having delved into the world of web development, I&apos;ve not
                  only acquired technical skills but also developed a keen eye
                  for detail and a problem-solving mindset. My journey began
                  with a deep fascination for creating interactive front-end
                  designs that seamlessly integrate with powerful back-end
                  functionalities. This drive has led me to explore and master
                  the React.js and Next.js frameworks, which enable me to build
                  cutting-edge web applications that provide an exceptional user
                  experience.
                </p>
              </div>
              <div>
                {details.map((detail, index) => {
                  return (
                    <li
                      key={index}
                      className={`py-3 list-none  border-[#eaeaea] ${
                        index === details.length - 1 ? "" : "border-b"
                      }`}
                    >
                      <span className="font-[600] mr-2">
                        {Object.keys(detail)}:
                      </span>
                      {Object.values(detail)}
                    </li>
                  );
                })}
                <ButtonComp
                  text="Download CV"
                  className="mt-3"
                  onClick={() => {
                    handleDownloadCV();
                  }}
                />
              </div>
            </div>
          </Layout>
          <Layout transparent={false}>
            <Heading text="Resume" subText="SUMMARY" />
            <div className="w-full flex max-md:flex-col max-md:gap-6 gap-12">
              <div className="flex-1">
                <h1 className="font-[600] text-2xl max-md:text-xl mb-6">
                  My Education
                </h1>
                {education.map((education, index) => {
                  return (
                    <ResumeCard
                      key={index}
                      title={education.title}
                      time={education.year}
                      institute={education.institue}
                      details={education.details}
                    />
                  );
                })}
              </div>
              <div className="flex-1">
                <h1 className="font-[600] text-2xl max-md:text-xl mb-6">
                  My Experience
                </h1>
                {experience.map((experience, index) => {
                  return (
                    <ResumeCard
                      key={index}
                      title={experience.title}
                      time={experience.year}
                      institute={experience.institue}
                      details={experience.details}
                    />
                  );
                })}
              </div>
            </div>
            <div>
              <h1 className="font-[600] text-2xl max-md:text-xl my-6">
                My Skills
              </h1>
              <div className="grid grid-cols-2 max-md:grid-cols-1 max-md:gap-6 gap-x-12 gap-y-8">
                {skills?.map((skill, index) => {
                  return (
                    <SkillComp
                      key={index}
                      title={skill.title}
                      percentage={skill?.percentage?.toString()}
                    />
                  );
                })}
              </div>
            </div>
            <ButtonComp
              text={`Download CV`}
              icon={<FileDownloadIcon />}
              onClick={() => {
                handleDownloadCV();
              }}
              center={true}
              className="mt-20"
              transparent={true}
            />
          </Layout>
          <Layout>
            <Heading text="My Work" subText="PORTFOLIO" />
            <div className="grid grid-cols-2 max-md:grid-cols-1 max-md:gap-6  gap-8">
              {projects?.map((project, index) => {
                return (
                  <ProjectCard
                    key={index}
                    image={project.image}
                    liveLink={project.liveLink}
                    githubLink={project.githubLink}
                  />
                );
              })}
            </div>
          </Layout>
          <Layout transparent={false}>
            <Heading text="Get in Touch" subText="CONTACT" />
            <div className="flex max-md:flex-col-reverse max-md:text-sm max gap-6">
              <div className="flex-1">
                <h1 className="text-xl font-[600]">ADDRESS</h1>
                <p>Karachi, Pakistan</p>
                <div className="flex flex-col gap-3 my-8">
                  <p className="flex items-center gap-1 m-0">
                    <CallIcon className="text-customPrimary" />
                    +92 332 6556262
                  </p>
                  <p className="flex items-center gap-1 m-0">
                    <WhatsAppIcon className="text-customPrimary" />
                    +92 332 6556262
                  </p>
                  <p className="flex items-center gap-1 m-0">
                    <MailIcon className="text-customPrimary" />
                    annasahmed1609@gmail.com
                  </p>
                </div>
                <h1 className="text-xl font-[600]">CONNECT WITH ME</h1>
                <div className="flex items-center gap-6">
                  {socialLinks.map((social: any, index: number) => {
                    return (
                      <p
                        className="text-[16px]/"
                        key={index}
                        onClick={() => {
                          handleSocialLinks(social.link, social.email);
                        }}
                      >
                        {social.icon}
                      </p>
                    );
                  })}
                </div>
              </div>
              <form className="flex-[3]">
                <h1 className="text-xl font-[600]">SEND US A NOTE</h1>
                <input
                  className="bg-customLight border border-customSemiLight w-[48%] max-md:w-full max-md:mr-0 mb-4 mr-[4%] px-2 py-3 rounded-lg "
                  placeholder="Name"
                  type="text"
                  required
                />
                <input
                  className="bg-customLight border border-customSemiLight w-[48%] max-md:w-full mb-4 px-2 py-3 rounded-lg "
                  placeholder="Email"
                  type="email"
                  required
                />
                <textarea
                  className="bg-customLight border border-customSemiLight w-full px-2 py-3 rounded-lg resize-none "
                  placeholder="Leave your comment"
                  name=""
                  id=""
                  // cols={30}
                  rows={4}
                  required
                ></textarea>
                <ButtonComp
                  text="Send Message"
                  center={true}
                  className="mt-6"
                />
              </form>
            </div>
          </Layout>
        </div>
      </main>
    </>
  );
}
