import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import LinkedInIcon from "@mui/icons-material/LinkedIn";
import GitHubIcon from "@mui/icons-material/GitHub";
import WhatsAppIcon from "@mui/icons-material/WhatsApp";
import MailIcon from "@mui/icons-material/Mail";
import ButtonComp from "@/components/buttonComp";
import Layout from "@/components/layout";
import Heading from "@/components/heading";
import ResumeCard from "@/components/resumeCard";
import SkillComp from "@/components/skillComp";
import FileDownloadIcon from "@mui/icons-material/FileDownload";
import { index } from "cheerio/lib/api/traversing";
import ProjectFrame from "@/components/projectFrame";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const navs = ["Home", "About Me", "Resume", "Portfolio", "Contact"];
  const details = [
    { Name: "Annas Ahmed" },
    { Email: "annasahmed1609@gmail.com" },
    { Age: "21" },
    { From: "Karachi, Pakistan" },
  ];
  const education = [
    {
      year: "2021-2025",
      title: "BSCS",
      institue: "University Of Karachi",
      details: "Currently pursuing third year",
    },
  ];
  const experience = [
    {
      year: "August 2022 - Present",
      title: "FREELANCING",
      institue: "Different Freelance Platforms",
      details: "More than 1 year experience in Freelancing",
    },
  ];
  const skills = [
    { title: "React Js", percentage: 80 },
    { title: "Next Js", percentage: 70 },
    { title: "HTML/CSS", percentage: 95 },
    { title: "JavaScript", percentage: 80 },
    { title: "Python", percentage: 75 },
    { title: "Node Js/Express Js", percentage: 50 },
  ];
  const socialLinks = [
    {
      icon: <WhatsAppIcon fontSize="small" />,
      link: "",
    },
    {
      icon: <MailIcon fontSize="small" />,
      link: "",
    },
    {
      icon: <GitHubIcon fontSize="small" />,
      link: "",
    },
    {
      icon: <LinkedInIcon fontSize="small" />,
      link: "",
    },
  ];
  const projects = [
    {
      urlId: "1zDAQlCZoezhDFHhIB7h6VHVtyLUc-lAi",
    },
    {
      urlId: "1LgXk0FoVVG52dIReGj67zPvic51NREnD",
    },
    {
      urlId: "1sj0cG2Kds0IGR4E0_C4deuUMM7o-DbL6",
    },
    // {
    //   urlId: "1uh4QVfW0mau7DdESkVz6YT11pL45dv-7",
    // },
    // {
    //   urlId: "1gozu2sdo17THQES5CAvWgB2F1mGd8yMg",
    // },

    // {
    //   urlId: "1_G0QBWapdWvNV_5Sy358Q3zB-SfFzOJW",
    // },
    // {
    //   urlId: "1divQzOJKBoiwdrOiJhMiKeww51VZDneF",
    // },
  ];
  return (
    <>
      <Head>
        <title>Annas Ahmed</title>
        <meta name="description" content="Generated by Annas Ahmed" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
      </Head>
      <main className="flex">
        <section className="w-[250px] fixed flex flex-col h-screen overflow-hidden justify-between pt-10 pb-6 items-center px-4/ bg-[#111418]">
          <div className="flex justify-center items-center flex-col gap-4 ">
            <Image
              src={require("../assets/profile.png")}
              alt="Profile Picture"
              className="w-[180px] border-[8px] rounded-[50%] border-[#343a40]"
            />
            <h1 className="text-customLight text-2xl">Annas Ahmed</h1>
          </div>
          <nav className="my-10 ">
            <ul className="flex flex-col gap-4">
              {navs.map((nav: string, index: number) => {
                return (
                  <li
                    className="px-3 cursor-pointer text-customSemiLight text-lg text-center hover:text-customPrimary"
                    key={index}
                  >
                    {nav}
                  </li>
                );
              })}
            </ul>
          </nav>
          <div className="flex   justify-between items-center px-12 text-customSemiLight ">
            {socialLinks.map((social: any, index: number) => {
              return (
                <p className="text-[8px]" key={index}>
                  {social.icon}
                </p>
              );
            })}
          </div>
        </section>
        <div className="w-[calc(100%-250px)] ml-auto">
          <section
            className={`flex-[8] /
            bg-[url(../assets/home_backgorund.jpeg)]
            bg-cover
            bg-no-repeat
            w-full
            h-screen
            `}
          >
            <div className="bg-[#252729] flex flex-col gap-8 justify-center items-center text-customLight bg-opacity-60 w-full h-screen">
              <h1 className="text-3xl font-[500]">Welcome</h1>
              <h1 className="text-5xl font-bold">I&apos;m Annas Ahmed.</h1>
              <h1 className="text-2xl">from Karachi, Pakistan</h1>
              <ButtonComp text="Hire Me" transparent={true} />
            </div>
          </section>
          <Layout>
            <Heading text="Know Me More" subText="ABOUT ME" />
            <div className="flex gap-12">
              <div>
                <h1 className="text-3xl font-[600]">
                  I&apos;m{" "}
                  <span className="text-customPrimary">Simone Olivia,</span> a
                  Web Developer
                </h1>
                <p>
                  I help you build brand for your business at an affordable
                  price. Thousands of clients have procured exceptional results
                  while working with our dedicated team. when an unknown printer
                  took a galley of type and scrambled it to make a type specimen
                  book.
                </p>
                <p>
                  Delivering work within time and budget which meets
                  client&apos;s requirements is our moto. Lorem Ipsum has been
                  the industrys standard dummy text ever when an unknown printer
                  took a galley.
                </p>
              </div>
              <div>
                {details.map((detail, index) => {
                  return (
                    <li
                      key={index}
                      className={`py-3 list-none  border-[#eaeaea] ${
                        index === details.length - 1 ? "" : "border-b"
                      }`}
                    >
                      <span className="font-[600] mr-2">
                        {Object.keys(detail)}:
                      </span>
                      {Object.values(detail)}
                    </li>
                  );
                })}
                <ButtonComp text="Download CV" className="mt-3" />
              </div>
            </div>
          </Layout>
          <Layout>
            <Heading text="Resume" subText="SUMMARY" />
            <div className="w-full flex gap-12">
              <div className="flex-1">
                <h1 className="font-[600] text-2xl mb-6">My Education</h1>
                {education.map((education, index) => {
                  return (
                    <ResumeCard
                      key={index}
                      title={education.title}
                      time={education.year}
                      institute={education.institue}
                      details={education.details}
                    />
                  );
                })}
              </div>
              <div className="flex-1">
                <h1 className="font-[600] text-2xl mb-6">My Experience</h1>
                {experience.map((experience, index) => {
                  return (
                    <ResumeCard
                      key={index}
                      title={experience.title}
                      time={experience.year}
                      institute={experience.institue}
                      details={experience.details}
                    />
                  );
                })}
              </div>
            </div>
            <div>
              <h1 className="font-[600] text-2xl my-6">My Skills</h1>
              <div className="grid grid-cols-2 gap-x-12 gap-y-8">
                {skills?.map((skill, index) => {
                  return (
                    <SkillComp
                      key={index}
                      title={skill.title}
                      percentage={skill?.percentage?.toString()}
                    />
                  );
                })}
              </div>
            </div>
            <ButtonComp
              text={`Download CV`}
              icon={<FileDownloadIcon />}
              center={true}
              className="mt-20"
              transparent={true}
            />
          </Layout>
          <Layout>
            <Heading text="My Work" subText="PORTFOLIO" />
            <div className="grid grid-cols-2 gap-8">
              {projects?.map((video, index) => {
                return <ProjectFrame video={video} />;
              })}
            </div>
          </Layout>
        </div>
      </main>
    </>
  );
}
